[1m[31mERROR   [0m root:ETL_log_table_validations.py:124 ‚ùå ETL log validation failed: Execution failed on sql '
                    SELECT T.*
                    FROM ETL_Process_Log T
                    WHERE ProcessLogId IN (
                        SELECT MAX(ProcessLogId)
                        FROM ETL_Process_Log
                        GROUP BY ComponentName
                    )
                ': ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'ETL_Process_Log'. (208) (SQLExecDirectW)")